config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :rooms do 
    resources :reviews, only: [:create, :update], module: :rooms
  end
  
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  POINTS = (1..5).to_a

  validates_uniqueness_of :user_id, scope: :room_id
  validates_presence_of :points, :user_id, :room_id
  validates_inclusion_of :points, in: POINTS

  belongs_to :user
  belongs_to :room, counter_cache: true

  def self.stars
    (average(:points) || 0).round
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  validates_presence_of :title
  validates_presence_of :slug

  friendly_id :title, use: [:slugged, :history]

  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room, dependent: :destroy


  mount_uploader :picture, PictureUploader
  friendly_id :title, use: [:slugged, :history]

  belongs_to :user

  def complete_name
    "#{title}, #{location}"
  end

  def self.search(query)
    if query.present?
      where(['location ILIKE :query OR title ILIKE :query OR description ILIKE :query', query: "%#{query}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :full_name, :location, presence: true
  validates :bio, length: { minimum: 30 }, allow_blank: false
  validates :email, format: { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ }, uniqueness: true

  scope :confirmed, -> { where('confirmed_at IS NOT NULL') }

  has_secure_password
  before_create :generate_token

  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def generate_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def self.authenticate(email, password)
    confirmed.find_by_email(email).try(:authenticate, password)
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''

    save!
  end

  def confirmed?
    confirmed_at.present?
  end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Validations
  include ActiveModel::Conversion

  extend ActiveModel::Naming
  extend ActiveModel::Translation

  attr_accessor :email, :password

  validates_presence_of :email, :password

  def initialize(session, attributes = {})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def authenticate
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def destroy
    @session[:user_id] = nil
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    return redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login') if user_signed_in?.nil? 
  end

  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by_confirmation_token(params[:token])

    if user.present?
      user.confirm!

      redirect_to user, notice: I18n.t('users.confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.limit(3)
  end
end

app/controllers/rooms/base_controller.rb
class Rooms::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_authentication

  private

  def room
    @room ||= Room.find(params[:id])
  end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < Rooms::BaseController
  before_action :require_authentication

  def create
    review = room.reviews.find_or_initialize_by(user_id: current_user.id)

    review.update(review_params)

    redirect_to room_path(room)
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end


  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  PER_PAGE = 10

  # GET /rooms or /rooms.json
  def index
    @search_query = params[:q]
    
    rooms = Room.search(@search_query)

    @rooms = Kaminari.paginate_array(RoomCollectionPresenter.new(rooms.all, self).to_ary).page(params[:page]).per(10)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    room_model = Room.friendly.find(params[:id])

    if user_signed_in?
      @room = RoomPresenter.new(room_model, self)
    end
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    @room = current_user.rooms.friendly.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    @room = current_user.rooms.friendly.find(params[:id])
  
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: 'edit'
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room = current_user.rooms.find(params[:id])
    @room.destroy

    redirect_to rooms_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy

  def new
    @session = UserSession.new(session)
  end

  def create
    @session = UserSession.new(session, params[:user_session])

    if @session.authenticate
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      SignupMailer.confirm_email(@user).deliver

      redirect_to @user, notice: 'Successfully registered!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'Successfully updated!'
    else
      render :update
    end
  end

  private

  def can_change
    unless user_signed_in?  && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :location, :password, :password_confirmation, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first, class: 'error_message'
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<div class='content'>
  <h1>Quartos recém postados</h1>
  <ul>
    <% @rooms.each do |room| %>
      <li><%= link_to room.complete_name, room %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %></li>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
    <li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.signup'), new_user_path %></li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colchonet</title>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:wght@200;300;400;500;600&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/850848e409.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%
=begin%>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
  </head>

  <body>
    <header>
      <div id='header-wrap'>
        <h1><%= link_to 'Colcho.net', root_path %></h1>

        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>
      </div>
    </header>

    <div>
      <% if notice.present? %>
        <p id='notice'><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p id='alert'><%= alert %></p>
      <% end %>

      <%= yield %> 
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <span class="star filled_star"></span>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <span class="star empty_star"></span>
    <% end %>

    <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point %>
      <%= f.label :points, value: point do %>
        <i class="icon-star fas fa-star"></i>
      <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
    <%= t('.login_to_review') %>
  </span>
<%  end%>

app/views/rooms/_room.html.erb
<article class="room">
  <h2 class="card-title"><%= link_to highlight(room.title, @search_query), room.route %></h2>

  <%= link_to(image_tag(room.thumb_url), room.picture_url) if room.has_picture? %>

  <%= render partial: 'review', locals: {room: room} %>

  <span class="created">
    <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
  </span>

  <p class="card-location">
    <span class="location">
      <%= link_to highlight(room.location, @search_query), "https://maps.google.com/?q=#{room.location}", target: :blank %>
    </span>
  </p>

  <p><%= highlight(room.description, @search_query) %></p>

  <% if belongs_to_user(room) %>
    <ul class="action-card">
      <li><%= link_to t('.edit'), edit_room_path(room.route), class: 'action-card-edit' %></li>
      <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: {confirm: t('dialogs.destroy')}, class: 'action-card-delete' %></li>
    </ul>
  <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1 id="register">Editing Room</h1>

<%= render 'form', room: @room %>

<p class="back-button">
  <%= link_to 'Show', @room %> |
  <%= link_to 'Back', rooms_path %>
</p>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1 id="register">
  <% if @search_query.present? %>
    <%= t '.search_results' %>
  <% else %>
    <%= t '.title' %>
  <% end %>
</h1>

<%= render @rooms %>
<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1 id="register">New Room</h1>

<%= render 'form', room: @room %>

<p class="back-button"><%= link_to 'Back', rooms_path %></p>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @session.errors.has_key? :base %>
  <div>
    <%= @session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @session do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @session, :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @session, :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    There are errors in the form, please check.
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @user, :location %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
  </p>
  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div class='content'>
  <h1 id='register'>Edit profile</h1>

  <%= render 'form' %>
  <p class='back-button'><%= link_to 'Back', @user, class: 'link-button' %></p>
</div>

app/views/users/new.html.erb
<div class='content'>
  <h1 id='register'>Register</h1>

  <%= render 'form' %>
  <p class='back-button'><%= link_to 'Back', root_path, class: 'link-button' %></p>
</div>

app/views/users/show.html.erb
<div class='content'>
  <h1 id='profile'>Profile</h1>

  <p>
    <strong><%= @user.full_name %></strong>
  </p>
  
  <br />

  <ul>
    <li>Location: <%= @user.location %> </li>
    <li>Bio: <%= @user.bio %> </li>
  </ul>

  <br />

  <%= link_to 'Edit profile', edit_user_path(@user), class: 'action-card-edit' %>
  <p class='back-button'><%= link_to 'Home', root_path, class: 'link-button' %></p>
</div>